spring.application.name=demo

spring.threads.virtual.enabled=true

spring.mongodb.database=test
spring.mongodb.uri=mongodb://root:password@localhost:27017/?retryWrites=true&maxIdleTimeMS=120000

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=NotificationEvent:com.example.demo.NotificationEvent

app.kafka.topic.name=the-topic
